# coding: utf-8

"""
    MSK-MIND REST API

    MSK-MIND REST API  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.query_api import QueryApi  # noqa: E501
from openapi_client.rest import ApiException


class TestQueryApi(unittest.TestCase):
    """QueryApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.query_api.QueryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_download(self):
        """Test case for download

        """
        pass

    def test_query(self):
        """Test case for query

        """
        pass


if __name__ == '__main__':
    unittest.main()
