# coding: utf-8

"""
    MSK-MIND REST API

    MSK-MIND REST API  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.introspect_api import IntrospectApi  # noqa: E501
from openapi_client.rest import ApiException


class TestIntrospectApi(unittest.TestCase):
    """IntrospectApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.introspect_api.IntrospectApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_columns(self):
        """Test case for get_columns

        """
        pass

    def test_get_databases(self):
        """Test case for get_databases

        """
        pass

    def test_get_tables(self):
        """Test case for get_tables

        """
        pass


if __name__ == '__main__':
    unittest.main()
