# coding: utf-8

"""
    MSK-MIND REST API

    MSK-MIND REST API  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.mind_response_string import MindResponseString  # noqa: E501
from openapi_client.rest import ApiException

class TestMindResponseString(unittest.TestCase):
    """MindResponseString unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test MindResponseString
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.mind_response_string.MindResponseString()  # noqa: E501
        if include_optional :
            return MindResponseString(
                status = 'OK', 
                summary = '0', 
                description = '0', 
                payload = '0'
            )
        else :
            return MindResponseString(
        )

    def testMindResponseString(self):
        """Test MindResponseString"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
