# coding: utf-8

"""
    MSK-MIND REST API

    MSK-MIND REST API  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.atlas_term_assignment_header import AtlasTermAssignmentHeader  # noqa: E501
from openapi_client.rest import ApiException

class TestAtlasTermAssignmentHeader(unittest.TestCase):
    """AtlasTermAssignmentHeader unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AtlasTermAssignmentHeader
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.atlas_term_assignment_header.AtlasTermAssignmentHeader()  # noqa: E501
        if include_optional :
            return AtlasTermAssignmentHeader(
                term_guid = '0', 
                relation_guid = '0', 
                description = '0', 
                display_text = '0', 
                expression = '0', 
                created_by = '0', 
                steward = '0', 
                source = '0', 
                confidence = 56, 
                status = 'DISCOVERED'
            )
        else :
            return AtlasTermAssignmentHeader(
        )

    def testAtlasTermAssignmentHeader(self):
        """Test AtlasTermAssignmentHeader"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
