# coding: utf-8

"""
    MSK-MIND REST API

    MSK-MIND REST API  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.mind_response_list_data_file import MINDResponseListDataFile  # noqa: E501
from openapi_client.rest import ApiException

class TestMINDResponseListDataFile(unittest.TestCase):
    """MINDResponseListDataFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test MINDResponseListDataFile
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.mind_response_list_data_file.MINDResponseListDataFile()  # noqa: E501
        if include_optional :
            return MINDResponseListDataFile(
                status = 'OK', 
                summary = '0', 
                description = '0', 
                payload = [
                    openapi_client.models.data_file.DataFile(
                        id = '0', 
                        path = '0', 
                        type = 'CLINICAL', 
                        create_time = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                    ]
            )
        else :
            return MINDResponseListDataFile(
        )

    def testMINDResponseListDataFile(self):
        """Test MINDResponseListDataFile"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
