# coding: utf-8

"""
    MSK-MIND REST API

    MSK-MIND REST API  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.atlas_classification import AtlasClassification  # noqa: E501
from openapi_client.rest import ApiException

class TestAtlasClassification(unittest.TestCase):
    """AtlasClassification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AtlasClassification
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.atlas_classification.AtlasClassification()  # noqa: E501
        if include_optional :
            return AtlasClassification(
                type_name = '0', 
                attributes = {
                    'key' : None
                    }, 
                entity_guid = '0', 
                entity_status = 'ACTIVE', 
                propagate = True, 
                validity_periods = [
                    openapi_client.models.time_boundary.TimeBoundary(
                        start_time = '0', 
                        end_time = '0', 
                        time_zone = '0', )
                    ], 
                remove_propagations_on_entity_delete = True
            )
        else :
            return AtlasClassification(
        )

    def testAtlasClassification(self):
        """Test AtlasClassification"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
