# coding: utf-8

"""
    MSK-MIND REST API

    MSK-MIND REST API  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.business_api import BusinessApi  # noqa: E501
from openapi_client.rest import ApiException


class TestBusinessApi(unittest.TestCase):
    """BusinessApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.business_api.BusinessApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_metadata(self):
        """Test case for get_metadata

        """
        pass

    def test_get_metadata_file_url(self):
        """Test case for get_metadata_file_url

        """
        pass


if __name__ == '__main__':
    unittest.main()
