# coding: utf-8

"""
    MSK-MIND REST API

    MSK-MIND REST API  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.operation_api import OperationApi  # noqa: E501
from openapi_client.rest import ApiException


class TestOperationApi(unittest.TestCase):
    """OperationApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.operation_api.OperationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_file_url(self):
        """Test case for get_file_url

        """
        pass

    def test_get_files(self):
        """Test case for get_files

        """
        pass


if __name__ == '__main__':
    unittest.main()
