# coding: utf-8

"""
    MSK-MIND REST API

    MSK-MIND REST API  # noqa: E501

    The version of the OpenAPI document: v0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.text_node import TextNode  # noqa: E501
from openapi_client.rest import ApiException

class TestTextNode(unittest.TestCase):
    """TextNode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TextNode
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.text_node.TextNode()  # noqa: E501
        if include_optional :
            return TextNode(
                node_type = 'ARRAY', 
                empty = True, 
                array = True, 
                null = True, 
                value_node = True, 
                container_node = True, 
                object = True, 
                missing_node = True, 
                pojo = True, 
                number = True, 
                integral_number = True, 
                floating_point_number = True, 
                short = True, 
                int = True, 
                long = True, 
                float = True, 
                double = True, 
                big_decimal = True, 
                big_integer = True, 
                textual = True, 
                boolean = True, 
                binary = True
            )
        else :
            return TextNode(
        )

    def testTextNode(self):
        """Test TextNode"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
